all: video_pubsub models

video_pubsub:
    mkdir -p video_pubsub/build
    cd video_pubsub/build && \
        cmake .. \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=../../install && \
        cmake --build . && \
        cmake --build . --target install

models:
    mkdir -p models/build
    cd models/build && \
        cmake .. \
            -DLIBTORCH_INSTALL_ROOT=${LIBTORCH_INSTALL_ROOT} \
            -DONNXRUNTIME_ROOTDIR=${ONNXRUNTIME_ROOTDIR} \
            -DUSE_CUDA_BACKEND=True \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_INSTALL_PREFIX=../../install && \
        cmake --build . && \
        cmake --build . --target install

run_video_pubsub:
    parallel --verbose --lb ::: \
             "./install/bin/video_publisher -k video/raw -c DEFAULT_CONFIG.json5 ../data/video.mp4" \
             "./install/bin/video_subscriber -k video/raw -c DEFAULT_CONFIG.json5"

run_sceneseg:
    # TensorRT
    parallel --verbose --lb ::: \
             "./install/bin/video_publisher -k video/input -c DEFAULT_CONFIG.json5 ../data/video.mp4" \
             "./install/bin/run_model ../data/models/SceneSeg_FP32.onnx -i video/input -o video/output -m segmentation -b tensorrt -p fp16 -c DEFAULT_CONFIG.json5" \
             "./install/bin/segment_subscriber -k video/input -s video/output -m scene -c DEFAULT_CONFIG.json5"
    # ONNX Runtime
    #parallel --verbose --lb ::: \
    #         "./install/bin/video_publisher -k video/input ../data/video.mp4" \
    #         "./install/bin/run_model ../data/models/SceneSeg_FP32.onnx -i video/input -o video/output -m segmentation" \
    #         "./install/bin/segment_subscriber -k video/input -s video/output -m scene"

run_domainseg:
    # TensorRT
    parallel --verbose --lb ::: \
             "./install/bin/video_publisher -k video/input -c DEFAULT_CONFIG.json5 ../data/video.mp4" \
             "./install/bin/run_model ../data/models/DomainSeg_FP32.onnx -i video/input -o video/output -m segmentation -b tensorrt -p fp16 -c DEFAULT_CONFIG.json5" \
             "./install/bin/segment_subscriber -k video/input -s video/output -m domain -c DEFAULT_CONFIG.json5"
    # ONNX Runtime
    #parallel --verbose --lb ::: \
    #         "./install/bin/video_publisher -k video/input ../data/video.mp4" \
    #         "./install/bin/run_model ../data/models/DomainSeg_FP32.onnx -i video/input -o video/output -m segmentation" \
    #         "./install/bin/segment_subscriber -k video/input -s video/output -m domain"

run_scene3d:
    # TensorRT
    parallel --verbose --lb ::: \
             "./install/bin/video_publisher -k video/input -c DEFAULT_CONFIG.json5 ../data/video.mp4" \
             "./install/bin/run_model ../data/models/Scene3D_FP32.onnx -i video/input -o video/output -m depth -b tensorrt -p fp16 -c DEFAULT_CONFIG.json5" \
             "./install/bin/depth_subscriber -k video/output -c DEFAULT_CONFIG.json5"
    # ONNX Runtime
    #parallel --verbose --lb ::: \
    #         "./install/bin/video_publisher -k video/input ../data/video.mp4" \
    #         "./install/bin/run_model ../data/models/Scene3D_FP32.onnx -i video/input -o video/output -m depth" \
    #         "./install/bin/video_subscriber -k video/output"

run_autospeed:
    # TensorRT with tracking
    parallel --verbose --lb ::: \
             "./install/bin/video_publisher -k video/input -c DEFAULT_CONFIG.json5 ../data/video.mp4" \
             "./install/bin/run_model ../data/models/autospeed.onnx -i video/input -o video/output -m autospeed -b tensorrt -p fp32 --homography ./test/homography.yaml -c DEFAULT_CONFIG.json5" \
             "./install/bin/autospeed_subscriber -v video/input -k video/output -c DEFAULT_CONFIG.json5"
    # ONNX Runtime with tracking
    # parallel --verbose --lb ::: \
    #         "./install/bin/video_publisher -k video/input -c DEFAULT_CONFIG.json5 ../data/video.mp4" \
    #         "./install/bin/run_model ../data/models/autospeed.onnx -i video/input -o video/output -m autospeed -b onnxruntime -p cpu --homography ./test/homography.yaml -c DEFAULT_CONFIG.json5" \
    #         "./install/bin/autospeed_subscriber -v video/input -k video/output -c DEFAULT_CONFIG.json5"

run_egolanes:
    # TensorRT
    parallel --verbose --lb ::: \
             "./install/bin/video_publisher -k video/input -c DEFAULT_CONFIG.json5 ../data/video.mp4" \
             "./install/bin/run_model ../data/models/EgoLanes_FP32.onnx -i video/input -o video/output -m egolanes -b tensorrt -p fp16 -c DEFAULT_CONFIG.json5" \
             "./install/bin/segment_subscriber -k video/input -s video/output -m egolanes -c DEFAULT_CONFIG.json5"
    # ONNX Runtime
    #parallel --verbose --lb ::: \
    #         "./install/bin/video_publisher -k video/input ../data/video.mp4" \
    #         "./install/bin/run_model ../data/models/EgoLanes_FP32.onnx -i video/input -o video/output -m egolanes" \
    #         "./install/bin/segment_subscriber -k video/input -s video/output -m egolanes"

clean:
    rm -rf install video_pubsub/build models/build
